context.modules = [
    {
        name = libpipewire-module-snapcast-discover
        args = {
             snapcast.discover-local = true
             stream.rules = [
                 {
                     matches = [
                        {
                            snapcast.ip = "~.*"
                        }
                     ]
                     actions = {
                         create-stream = {
                             node.name = "Snapcast"
                             snapcast.stream-name = "kusanagi"
                         }
                     }
                 }
             ]
        }
    }
]
